---
- name: System update (OS family - Debian)
  apt:
    update-cache: yes
  become: yes
  changed_when: False

- name: System upgrade (OS family - Debian)
  apt:
    upgrade: dist
  become: yes
  when: update_packages

- name: Install packages (OS family - Debian)
  apt:
    name: "{{ system_packages }}"
  become: yes
  when: check_system_packages
