---
- name: Upgrate all packages (OS family - RedHat )
  dnf:
    name: '*'
    state: latest
  become: yes
  when: update_packages

- name: Install packages (OS family - RedHat)
  dnf:
    name: "{{ system_packages }}"
    state: present
  become: yes
  when: check_system_packages
