---
- name: Upgrate all packages (OS family - RedHat )
  yum:
    name: '*'
    state: latest
  become: yes
  when: update_packages

- name: Install packages (OS family - RedHat)
  yum:
    name: "{{ system_packages }}"
  become: yes
  when: check_system_packages
